<?php
return array(
    'original' => array(
        'recompress_target' => '0.9999',
        'recompress_min' => '40',
        'recompress_max' => '95',
        'recompress_loops' => '6',
        'recompress_method' => 'ssim',
    ),
    'fullsize' => array(
        'resize_max_quality' => '100',
        'resize_width' => '1920',
        'resize_height' => '1080',
        'resize_square' => '0',
        'recompress_target' => '0.9999',
        'recompress_min' => '40',
        'recompress_max' => '95',
        'recompress_loops' => '6',
        'recompress_method' => 'ssim',
    ),
    'middsize' => array(
        'resize_max_quality' => '100',
        'resize_width' => '960',
        'resize_height' => '960',
        'resize_square' => '0',
        'recompress_target' => '0.9999',
        'recompress_min' => '40',
        'recompress_max' => '95',
        'recompress_loops' => '6',
        'recompress_method' => 'ssim',
    ),
    'thumbnails' => array(
        'resize_max_quality' => '100',
        'resize_width' => '360',
        'resize_height' => '360',
        'resize_square' => '0',
        'recompress_target' => '0.9999',
        'recompress_min' => '40',
        'recompress_max' => '95',
        'recompress_loops' => '6',
        'recompress_method' => 'ssim',
    ),
    'square_thumbnails' => array(
        'resize_max_quality' => '100',
        'resize_width' => '360',
        'resize_height' => '360',
        'resize_square' => '1',
        'recompress_target' => '0.9999',
        'recompress_min' => '40',
        'recompress_max' => '95',
        'recompress_loops' => '6',
        'recompress_method' => 'ssim',
    )
);